### ISSUE TITLE
Republish to npm

### ISSUE THREAD

**Issue by daneroo** [Swizec/d3blackbox#4]
`useD3 ` is not exported (or defined) in current npm published version
Perhaps this is because you don't want to depend on `React.useEffect()`?

**Comment by Swizec** [comment]
Thanks for the heads up @daneroo! Sorry for the late fix but you were totally right. Forgot to republish after exporting `useD3` 🤦‍♂️

Reason it exists is so it wraps together `useRef` and `useEffect`. Less code to type :)
